version: "3.9"

services:
  sdk:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./secrets/fireblocks_secret.key:/app/secrets/fireblocks_secret.key:ro
    command: npm start
